zkcloud:
  host: "loadcloud01.getanton.com"
  port: 443

image:
  repo: "us-west1-docker.pkg.dev/zerok-dev/zerok-cli/zk-wsp-client"
  tag: "latest"
  imagePullPolicy: Always

routes:
  zkCloudAddr: ""
deployment:
  replicas: 1
  zkWspClient:
    image:
      repository: nginx
      tag: dev
    imagePullPolicy: Always
kubernetesClusterDomain: cluster.local
zkWspClient:
  ports:
  - port: 8987
    protocol: TCP
    targetPort: 8987
  type: ClusterIP
