host: 0.0.0.0
port: 8989
timeout: 30
idleTimeout: 30
poolMaxSize: 100
zkcloud:
  host: localhost
  port: 8883
  loginPath: /v1/i/auth/wsplogin
  connectionSyncInterval: 30
  connectionSyncPath: /v1/i/clustermeta/updateConnection
logs:
  color: true
  level: DEBUG