apiVersion: v1
data:
  wsp-config.yaml: |+
    host: 0.0.0.0
    port : 8987
    timeout : 3000
    target:
      url: ws://api.avinpx07.getanton.com:80/register
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    poolIdleSize: 5
    poolMaxSize: 100
    maxRetryInterval: 300
    defaultRetryInterval: 30
kind: ConfigMap
metadata:
  name: zk-wsp-client
  namespace: zk-client