apiVersion: v1
data:
  wsp-config.yaml: |+
    host: 127.0.0.1
    port : 8987
    timeout : 3000
    target:
      url: wss://api.loadcloud01.getanton.com:443/register
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    poolidlesize: 5
    poolmaxsize: 100
kind: ConfigMap
metadata:
  name: zk-wsp-client
  namespace: zk-client