apiVersion: v1
data:
  config.yaml: |+
    host: 0.0.0.0
    port : 8987
    timeout : 3000
    target:
      url: wss://api.loadcloud01.getanton.com:443/register
      clusterSecretName: cluster-info
      clusterKeyData: clusterKey
      clusterKeyNamespace: zk-client
      maxRetries: 3
    poolIdleSize: 5
    poolMaxSize: 100
    maxRetryInterval: 300
    defaultRetryInterval: 30
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-wsp-client
  namespace: zk-client