apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-wsp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-wsp-client
  template:
    metadata:
      labels:
        app: zk-wsp-client
    spec:
      serviceAccountName: zk-wsp-client
      containers:
        - name: zk-wsp-client
          image: wsp-client:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: wsp-config
              mountPath: /zk/config
          ports:
            - containerPort: 8987
      volumes:
        - name: wsp-config
          configMap:
            name: zk-wsp-client
