apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-wsp-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-wsp-client
  template:
    metadata:
      labels:
        app: zk-wsp-client
    spec:
      containers:
        - name: zk-wsp-client
          image: us-west1-docker.pkg.dev/zerok-dev/stage/zk-wsp-client:0.0.2
          imagePullPolicy: Always
          volumeMounts:
            - name: wsp-config
              mountPath: /opt
          ports:
            - containerPort: 8981
      volumes:
        - name: wsp-config
          configMap:
            name: zk-wsp-client-configmap
