# Adds namespace to all resources.
namespace: zk-client
resources:
- ./deployment.yaml
- ./service.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wsp-client
  newName: us-west1-docker.pkg.dev/zerok-dev/stage/zk-wsp-client
  newTag: dev
