apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zk-wsp-secrets-rolebinding
  namespace: zk-client
subjects:
  - kind: ServiceAccount
    name: zk-wsp-client
    namespace: zk-client
roleRef:
  kind: Role
  name: zk-wsp-secrets-role
  apiGroup: rbac.authorization.k8s.io