apiVersion: v1
kind: Service
metadata:
  name: zk-wsp-client
spec:
  selector:
    app: zk-wsp-client
  ports:
    - protocol: TCP
      port: 8987
      targetPort: 8987
      name: legacy
    - protocol: TCP
      port: 80
      targetPort: 8987
      name: default
  type: ClusterIP