host : 127.0.0.1                    # Address to bind the HTTP server
port : 8987                          # Port to bind the HTTP server
timeout : 3000
target:
  url: ws://localhost:8989/register
  clusterSecretName: cluster-info
  clusterKeyData: clusterKey
  clusterKeyNamespace: zk-client
  maxRetries: 3
  secretKey: a5f882c0934789c6d1f047b90517e2217ce2ca81cced19a0639c2f502669e715 # Only provide this while testing in local. On cluster this will read from secret.
poolIdleSize: 5
poolMaxSize: 100
maxRetryInterval: 300
defaultRetryInterval: 30