host : 0.0.0.0                     # Address to bind the HTTP server
port : 8987                          # Port to bind the HTTP server
timeout : 3000
targets:
  - ws://localhost:8989/register
poolIdleSize: 5
poolMaxSize: 100