id: 123
host : 127.0.0.1                     # Address to bind the HTTP server
port : 8987                          # Port to bind the HTTP server
timeout : 3000
targets:
  - ws://localhost:8989/register
poolIdleSize: 1
poolMaxSize: 100
secretKey: 12