apiVersion: v1
data:
  wsp-config.yaml: |+
    host: 0.0.0.0
    port: 8989
    timeout: 30
    idleTimeout: 1800
    poolMaxSize: 100
    zkcloud:
      host: zk-auth.zkcloud.svc.cluster.local
      port: 80
      loginPath: /v1/i/auth/wsplogin
    logs:
      color: true
      level: DEBUG
kind: ConfigMap
metadata:
  name: zk-wsp-server
  namespace: zkcloud