# Adds namespace to all resources.
namespace: zkcloud
resources:
- ./deployment.yaml
- ./ingress.yaml
- ./service.yaml
- ./configmap.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: wsp-server
  newName: us-west1-docker.pkg.dev/zerok-dev/stage/zk-wsp-server
  newTag: dev
