apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zk-wsp.fullname" . }}-deployment
  labels:
  {{- include "zk-wsp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: zk-wsp-client
    {{- include "zk-wsp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: zk-wsp-client
      {{- include "zk-wsp.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zk-wsp.fullname" . }}-client
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: "{{ .Values.image.repo}}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.imagePullPolicy }}
        name: zk-wsp-client
        ports:
        - containerPort: 8987
        resources: {}
        volumeMounts:
        - mountPath: /opt
          name: wsp-config
      volumes:
      - configMap:
          name: {{ include "zk-wsp.fullname" . }}-client
        name: wsp-config