apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zk-wsp.fullname" . }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: zk-wsp-secrets-role
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: zk-wsp-secrets-rolebinding
subjects:
  - kind: ServiceAccount
    name: {{ include "zk-wsp.fullname" . }}
roleRef:
  kind: Role
  name: zk-wsp-secrets-role
  apiGroup: rbac.authorization.k8s.io
