apiVersion: v1
kind: Service
metadata:
  name: {{ include "zk-wsp.fullname" . }}-client
  labels:
  {{- include "zk-wsp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.zkWspClient.type }}
  selector:
    app: zk-wsp-client
  {{- include "zk-wsp.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.zkWspClient.ports | toYaml | nindent 2 -}}