name: prod-build-push (Client)
on:
  push:
    tags: #r/<ENVIRONMENT>/<DOCKER-TAG-OR-VERSION>
      - 'prod/**'

#  # Uncomment the following code for testing
#  workflow_dispatch:
#    inputs:
#      DOCKER_TAG:
#        description: 'Docker Image Tag'
#        required: true
#        default: '0.0.9-helmtest'
#      ENV:
#        description: 'ENV'
#        required: true
#        default: 'poc'
jobs:
  init:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-prod-init.yml@main
    with:
      ENVIRONMENT: ${{ github.event.inputs.ENV }}
      GIT_TAG: ${{ github.ref }}
      DOCKER_TAG: ${{ github.event.inputs.DOCKER_TAG }}

  build-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-build-push-multiarch.yml@main
    with:
      VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.ENVIRONMENT }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      DOCKER_FILE_NAME: 'Dockerfile-Client'
      MAKE_TARGET: 'ci-cd-build-client'
      APP_NAME_VAR: 'APP_NAME_CLIENT'
    secrets:
      GKE_SA_KEY: ${{ secrets.GKE_SA_KEY_PROD }}
    needs: init

  # build helm charts and publish to helm repository
  helm-push:
    uses: zerok-ai/zk-git-actions/.github/workflows/zk-helm-publish.yml@main
    with:
      HELM_VERSION: ${{ needs.init.outputs.VERSION }}
      ENVIRONMENT: ${{ needs.init.outputs.ENVIRONMENT }}
      DOCKER_IDENTIFIER: ${{ needs.init.outputs.ENVIRONMENT }}
      HELM_BUCKET_NAME: ${{ needs.init.outputs.HELM_BUCKET_NAME }}
      HELM_BUCKET_URL: ${{ needs.init.outputs.HELM_BUCKET_URL }}
      PROJECT_ID: ${{ needs.init.outputs.PROJECT_ID }}
      APP_NAME_VAR: 'APP_NAME_CLIENT'
    secrets:
      AWS_ACCESS_ID: ${{ secrets.AWS_ACCESS_ID }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
    needs: [init,build-push]
